
[default.extend-words]
vas = "vas"
Pase = "Pase"
PN = "PN"
GARD = "GARD"
ND = "ND"
superioris = "superioris"
Ptd = "Ptd"
RELA = "RELA"
HACE = "HACE"
pointes = "pointes"
Ags = "Ags"
ALS = "ALS"
STIL = "STIL"
mexicanus = "mexicanus"
formate = "formate"
terminalis = "terminalis"
CACH = "CACH"
langual = "langual"
Weill = "Weill"
asteroides = "asteroides"
Pilar = "Pilar"
hom = "hom"
FND = "FND"
ABL = "ABL"
BA = "BA"
contagiosum = "contagiosum"
Ser = "Ser"
migrans = "migrans"
miliary = "miliary"
americanus = "americanus"
Thm = "Thm"
KNO = "KNO"
ANE = "ANE"
Winn = "Winn"
Ende = "Ende"
